# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['app.py'],
    pathex=[],
    binaries=[],
    datas=[('templates', 'templates'), ('static', 'static'), ('migrations', 'migrations')],
    hiddenimports=[
        'logging',
        'logging.config',
        'flask',
        'flask_sqlalchemy',
        'flask_migrate',
        'flask_wtf',
        'wtforms',
        'openpyxl',
        'openpyxl.cell',
        'openpyxl.styles',
        'openpyxl.utils',
        'openpyxl.writer.excel',
        'openpyxl.xml',
        'PIL',
        'werkzeug',
        'jinja2',
        'jinja2.ext',
        'sqlalchemy',
        'sqlalchemy.sql.default_comparator',
        'sqlalchemy.dialects.sqlite',
        'models',
        'utils',
        'config',
        'routes',
        'routes.auth',
        'routes.birthdays',
        'routes.finances',
        'routes.inventory',
        'routes.main',
        'routes.members',
        'routes.payouts',
        'routes.protocols',
        'routes.reports',
        'routes.settings',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='profsouz',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity='-',
    entitlements_file=None,
)
