"""add finance distribution

Revision ID: 32986ec31ad5
Revises: ea1e3d9707b6
Create Date: 2026-07-18 13:06:49.794200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32986ec31ad5'
down_revision = 'ea1e3d9707b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_distribution_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finance_record_distribution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['finance_record.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['finance_distribution_rule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('finance_record_distribution')
    op.drop_table('finance_distribution_rule')
    # ### end Alembic commands ###
