"""add template background image

Revision ID: 46065ddb82d3
Revises: 689fb4385545
Create Date: 2026-07-18 16:20:24.796537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46065ddb82d3'
down_revision = '689fb4385545'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_template', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
