"""add pptx template fields

Revision ID: 49c0f38c325b
Revises: 46065ddb82d3
Create Date: 2026-07-18 16:35:00.230858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49c0f38c325b'
down_revision = '46065ddb82d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pptx_path', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('pptx_shape_map', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_template', schema=None) as batch_op:
        batch_op.drop_column('pptx_shape_map')
        batch_op.drop_column('pptx_path')

    # ### end Alembic commands ###
