"""finance_module

Revision ID: 4fee4c896067
Revises: 49c0f38c325b
Create Date: 2026-07-21 09:48:28.210859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fee4c896067'
down_revision = '49c0f38c325b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_year',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('ppo_opening', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('charity_opening', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('mpo_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('opo_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ppo_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('charity_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year')
    )
    op.create_table('finance_commission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['year_id'], ['finance_year.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finance_expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('fund', sa.String(length=20), nullable=False),
    sa.Column('protocol_number', sa.String(length=50), nullable=True),
    sa.Column('protocol_date', sa.Date(), nullable=True),
    sa.Column('protocol_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("fund IN ('ppo', 'charity')", name='ck_finance_expense_fund'),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocol.id'], ),
    sa.ForeignKeyConstraint(['year_id'], ['finance_year.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finance_month',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('mpo_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('opo_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ppo_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('charity_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('date_received', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['year_id'], ['finance_year.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year_id', 'month', name='uq_finance_month_year_month')
    )
    op.drop_table('finance_distribution_rule')
    op.drop_table('event')
    op.drop_table('document_template')
    op.drop_table('event_helper')
    op.drop_table('member_award')
    op.drop_table('finance_record_distribution')
    op.drop_table('event_expense')
    op.drop_table('finance_record')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_record',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=300), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), nullable=True),
    sa.Column('fund_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_expense',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('event_id', sa.INTEGER(), nullable=False),
    sa.Column('article', sa.VARCHAR(length=200), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finance_record_distribution',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('record_id', sa.INTEGER(), nullable=False),
    sa.Column('rule_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['finance_record.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['finance_distribution_rule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member_award',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('member_id', sa.INTEGER(), nullable=False),
    sa.Column('template_id', sa.INTEGER(), nullable=False),
    sa.Column('issued_at', sa.DATE(), nullable=False),
    sa.Column('note', sa.VARCHAR(length=300), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['document_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_helper',
    sa.Column('event_id', sa.INTEGER(), nullable=False),
    sa.Column('member_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'member_id')
    )
    op.create_table('document_template',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=30), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('body', sa.TEXT(), nullable=False),
    sa.Column('order', sa.INTEGER(), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('image_path', sa.VARCHAR(length=300), nullable=True),
    sa.Column('pptx_path', sa.VARCHAR(length=300), nullable=True),
    sa.Column('pptx_shape_map', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('protocol_id', sa.INTEGER(), nullable=True),
    sa.Column('file_path', sa.VARCHAR(length=300), nullable=True),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finance_distribution_rule',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('percent', sa.NUMERIC(precision=5, scale=2), nullable=False),
    sa.Column('order', sa.INTEGER(), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.Column('is_primary', sa.BOOLEAN(), nullable=True),
    sa.Column('is_bank_commission', sa.BOOLEAN(), nullable=True),
    sa.Column('parent_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('finance_month')
    op.drop_table('finance_expense')
    op.drop_table('finance_commission')
    op.drop_table('finance_year')
    # ### end Alembic commands ###
