"""add document templates and member awards

Revision ID: 689fb4385545
Revises: 3cb02e51e987
Create Date: 2026-07-18 15:57:41.449930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '689fb4385545'
down_revision = '3cb02e51e987'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member_award',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('issued_at', sa.Date(), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['document_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warranty_term_years', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('write_off_term_years', sa.Integer(), nullable=True))
        batch_op.drop_column('storage_term_years')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_term_years', sa.INTEGER(), nullable=True))
        batch_op.drop_column('write_off_term_years')
        batch_op.drop_column('warranty_term_years')

    op.drop_table('member_award')
    op.drop_table('document_template')
    # ### end Alembic commands ###
