"""add payout categories

Revision ID: 8dde0cb99f50
Revises: ec480aba281a
Create Date: 2026-07-18 12:42:47.236274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dde0cb99f50'
down_revision = 'ec480aba281a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payout_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payout_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['payout_type_id'], ['payout_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_payout_category', 'payout_category', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payout', schema=None) as batch_op:
        batch_op.drop_constraint('fk_payout_category', type_='foreignkey')
        batch_op.drop_column('category_id')

    op.drop_table('payout_category')
    # ### end Alembic commands ###
