"""add organization positions

Revision ID: ea1e3d9707b6
Revises: 8dde0cb99f50
Create Date: 2026-07-18 13:02:17.178154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea1e3d9707b6'
down_revision = '8dde0cb99f50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_position_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_member_organization_position', 'position', ['organization_position_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_constraint('fk_member_organization_position', type_='foreignkey')
        batch_op.drop_column('organization_position_id')

    op.drop_table('position')
    # ### end Alembic commands ###
